# Generated by Django 4.1.4 on 2023-01-16 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competitors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('country', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('abbreviation', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport_event_id', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField(blank=True)),
                ('home_name', models.CharField(max_length=255)),
                ('home_country', models.CharField(max_length=255)),
                ('away_name', models.CharField(max_length=255)),
                ('away_country', models.CharField(max_length=255)),
                ('venue', models.CharField(blank=True, max_length=255)),
                ('probability_home_team_winner', models.FloatField()),
                ('probability_draw', models.FloatField()),
                ('probability_away_team_winner', models.FloatField()),
                ('result', models.FloatField(blank=True, max_length=255)),
                ('result_type', models.CharField(blank=True, max_length=255)),
                ('competition_name', models.CharField(max_length=255)),
            ],
        ),
    ]
